version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "4987:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
